#!/bin/bash

# Parse command line arguments
RESULTS_DIR_ARG="${1:-}"  # Get first command line argument if provided

#SBATCH --job-name=evaluate_aesthetic_quality
#SBATCH --gres=gpu:40gb:1
#SBATCH --constraint=ampere
#SBATCH --cpus-per-task=8
#SBATCH --mem=150G
#SBATCH --ntasks=1
#SBATCH --time=12:00:00
#SBATCH --output=/network/scratch/j/jhas/aesthetic_eval-%j.out
#SBATCH --error=/network/scratch/j/jhas/aesthetic_eval-%j.err

# Create logs directory if it doesn't exist
mkdir -p logs

# Print job information
echo "Job ID: $SLURM_JOB_ID"
echo "Job Name: $SLURM_JOB_NAME"
echo "Node: $SLURMD_NODENAME"
echo "Start Time: $(date)"
echo "Working Directory: $(pwd)"
echo "SLURM_TMPDIR: $SLURM_TMPDIR"
echo "Output will be saved to: /network/scratch/j/jhas/aesthetic_eval-${SLURM_JOB_ID}.out"
echo "----------------------------------------"

# Load modules
module load python/3.10
module load cuda/11.8
module load gcc/9.3.0

# Set up environment
export PYTHONPATH=$PYTHONPATH:./
export CUDA_VISIBLE_DEVICES=0

# CUDA environment variables for better memory management
export PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:512
export PYTORCH_NO_CUDA_MEMORY_CACHING=1

# Print CUDA information for debugging
echo "CUDA_VISIBLE_DEVICES: $CUDA_VISIBLE_DEVICES"
echo "Available GPUs:"
nvidia-smi --list-gpus 2>/dev/null || echo "nvidia-smi not available"

# 1. Copy project files to compute node's temporary directory
echo "Copying project files to $SLURM_TMPDIR..."
cp -r $SLURM_SUBMIT_DIR/* $SLURM_TMPDIR/

# 2. Set up virtual environment on compute node
echo "Setting up virtual environment on compute node..."
python -m venv venv
source venv/bin/activate

# 3. Install dependencies
echo "Installing dependencies..."
pip install --upgrade pip
pip install -r requirements.txt

# Verify installation of key packages for aesthetic evaluation
echo "Verifying key package installations..."
python -c "import torch; import open_clip; import numpy; import tqdm; print('Key packages imported successfully')"

# 4. Download aesthetic model weights if needed
echo "Checking for aesthetic model weights..."
if [ ! -d "aesthetic-predictor" ]; then
    echo "Downloading aesthetic model weights..."
    mkdir -p aesthetic-predictor
    
    # Download the required model weights
    wget -O aesthetic-predictor/sa_0_4_vit_l_14_linear.pth \
        https://github.com/LAION-AI/aesthetic-predictor/raw/main/sa_0_4_vit_l_14_linear.pth
    
    wget -O aesthetic-predictor/sa_0_4_vit_b_32_linear.pth \
        https://github.com/LAION-AI/aesthetic-predictor/raw/main/sa_0_4_vit_b_32_linear.pth
    
    wget -O aesthetic-predictor/sa_0_4_vit_b_16_linear.pth \
        https://github.com/LAION-AI/aesthetic-predictor/raw/main/sa_0_4_vit_b_16_linear.pth
    
    echo "Model weights downloaded successfully."
else
    echo "Aesthetic model weights directory already exists, skipping download..."
fi

# 5. Configuration parameters
# Default results directory - can be overridden with command line argument
if [ -n "$RESULTS_DIR_ARG" ]; then
    # Use command line argument if provided
    RESULTS_DIR="$RESULTS_DIR_ARG"
else
    # Otherwise use environment variable or default
    RESULTS_DIR="${RESULTS_DIR:-results/verifier_wo_reasoning_new_claim_gen_test_OpenGVLab_InternVL3-14B_150_1_8_8_2_with_verifier_EQ_scorer_top_4_filtering_spatial_beam_search}"
fi

CLIP_MODEL="ViT-B/32"
AESTHETIC_MODEL="vit_b_32"

echo "Configuration:"
echo "  Results Directory: $RESULTS_DIR"
echo "  CLIP Model: $CLIP_MODEL"
echo "  Aesthetic Model: $AESTHETIC_MODEL"
echo "  (Output filename will be auto-generated based on results directory name)"
echo ""

# Check if results directory exists
if [ ! -d "$RESULTS_DIR" ]; then
    echo "ERROR: Results directory does not exist: $RESULTS_DIR"
    exit 1
fi

# Create output directory for results JSON
mkdir -p results

# 6. Build and execute the command
cmd="python utils/evaluate_perceptual_quality.py \
  $RESULTS_DIR \
  --clip_model $CLIP_MODEL \
  --aesthetic_model $AESTHETIC_MODEL \
  --device cuda"

echo "Running command: $cmd"
echo "----------------------------------------"

# Execute the command
eval $cmd

# Capture the actual output filename generated by the Python script
ACTUAL_OUTPUT=$(python -c "
import sys
from pathlib import Path
results_dir = '$RESULTS_DIR'
results_name = Path(results_dir).name
if not results_name:
    results_name = Path(results_dir).parent.name
print(f'results/aesthetic_scores_{results_name}.json')
")

# 7. Copy results back to submission directory
if [ $? -eq 0 ]; then
    echo "Job completed successfully!"
    
    # Copy results back if they exist
    if [ -f "$ACTUAL_OUTPUT" ]; then
        echo "Copying results back to submission directory..."
        cp "$ACTUAL_OUTPUT" "$SLURM_SUBMIT_DIR/results/"
        echo "Results copied to: $SLURM_SUBMIT_DIR/results/$(basename $ACTUAL_OUTPUT)"
    else
        echo "Warning: Output file not found: $ACTUAL_OUTPUT"
    fi
    
    # Copy aesthetic-predictor weights if downloaded
    if [ -d "aesthetic-predictor" ]; then
        cp -r aesthetic-predictor "$SLURM_SUBMIT_DIR/"
        echo "Model weights copied back to submission directory."
    fi
else
    echo "Job failed with exit code $?"
fi

echo "End Time: $(date)"
echo "-------------------- Finished executing script --------------------"

